// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Fri Aug 17 15:29:50 EEST 2012
// generated file: do not modify
package com.xlend.orm;

import com.xlend.orm.dbobject.DbObject;
import com.xlend.orm.dbobject.ForeignKeyViolationException;
import com.xlend.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Xjobcard extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer xjobcardId = null;
    private Integer xemployeeId = null;
    private Date carddate = null;
    private Date weekEnding = null;
    private String job1Day1 = null;
    private String job2Day1 = null;
    private String job3Day1 = null;
    private String job4Day1 = null;
    private String job5Day1 = null;
    private Integer machineId1Day1 = null;
    private Integer machineId2Day1 = null;
    private Integer machineId3Day1 = null;
    private Integer machineId4Day1 = null;
    private Integer machineId5Day1 = null;
    private String job1Day2 = null;
    private String job2Day2 = null;
    private String job3Day2 = null;
    private String job4Day2 = null;
    private String job5Day2 = null;
    private Integer machineId1Day2 = null;
    private Integer machineId2Day2 = null;
    private Integer machineId3Day2 = null;
    private Integer machineId4Day2 = null;
    private Integer machineId5Day2 = null;
    private String job1Day3 = null;
    private String job2Day3 = null;
    private String job3Day3 = null;
    private String job4Day3 = null;
    private String job5Day3 = null;
    private Integer machineId1Day3 = null;
    private Integer machineId2Day3 = null;
    private Integer machineId3Day3 = null;
    private Integer machineId4Day3 = null;
    private Integer machineId5Day3 = null;
    private String job1Day4 = null;
    private String job2Day4 = null;
    private String job3Day4 = null;
    private String job4Day4 = null;
    private String job5Day4 = null;
    private Integer machineId1Day4 = null;
    private Integer machineId2Day4 = null;
    private Integer machineId3Day4 = null;
    private Integer machineId4Day4 = null;
    private Integer machineId5Day4 = null;
    private String job1Day5 = null;
    private String job2Day5 = null;
    private String job3Day5 = null;
    private String job4Day5 = null;
    private String job5Day5 = null;
    private Integer machineId1Day5 = null;
    private Integer machineId2Day5 = null;
    private Integer machineId3Day5 = null;
    private Integer machineId4Day5 = null;
    private Integer machineId5Day5 = null;
    private String job1Day6 = null;
    private String job2Day6 = null;
    private String job3Day6 = null;
    private String job4Day6 = null;
    private String job5Day6 = null;
    private Integer machineId1Day6 = null;
    private Integer machineId2Day6 = null;
    private Integer machineId3Day6 = null;
    private Integer machineId4Day6 = null;
    private Integer machineId5Day6 = null;
    private String job1Day7 = null;
    private String job2Day7 = null;
    private String job3Day7 = null;
    private String job4Day7 = null;
    private String job5Day7 = null;
    private Integer machineId1Day7 = null;
    private Integer machineId2Day7 = null;
    private Integer machineId3Day7 = null;
    private Integer machineId4Day7 = null;
    private Integer machineId5Day7 = null;

    public Xjobcard(Connection connection) {
        super(connection, "xjobcard", "xjobcard_id");
        setColumnNames(new String[]{"xjobcard_id", "xemployee_id", "carddate", "week_ending", "job1_day1", "job2_day1", "job3_day1", "job4_day1", "job5_day1", "machine_id1_day1", "machine_id2_day1", "machine_id3_day1", "machine_id4_day1", "machine_id5_day1", "job1_day2", "job2_day2", "job3_day2", "job4_day2", "job5_day2", "machine_id1_day2", "machine_id2_day2", "machine_id3_day2", "machine_id4_day2", "machine_id5_day2", "job1_day3", "job2_day3", "job3_day3", "job4_day3", "job5_day3", "machine_id1_day3", "machine_id2_day3", "machine_id3_day3", "machine_id4_day3", "machine_id5_day3", "job1_day4", "job2_day4", "job3_day4", "job4_day4", "job5_day4", "machine_id1_day4", "machine_id2_day4", "machine_id3_day4", "machine_id4_day4", "machine_id5_day4", "job1_day5", "job2_day5", "job3_day5", "job4_day5", "job5_day5", "machine_id1_day5", "machine_id2_day5", "machine_id3_day5", "machine_id4_day5", "machine_id5_day5", "job1_day6", "job2_day6", "job3_day6", "job4_day6", "job5_day6", "machine_id1_day6", "machine_id2_day6", "machine_id3_day6", "machine_id4_day6", "machine_id5_day6", "job1_day7", "job2_day7", "job3_day7", "job4_day7", "job5_day7", "machine_id1_day7", "machine_id2_day7", "machine_id3_day7", "machine_id4_day7", "machine_id5_day7"});
    }

    public Xjobcard(Connection connection, Integer xjobcardId, Integer xemployeeId, Date carddate, Date weekEnding, String job1Day1, String job2Day1, String job3Day1, String job4Day1, String job5Day1, Integer machineId1Day1, Integer machineId2Day1, Integer machineId3Day1, Integer machineId4Day1, Integer machineId5Day1, String job1Day2, String job2Day2, String job3Day2, String job4Day2, String job5Day2, Integer machineId1Day2, Integer machineId2Day2, Integer machineId3Day2, Integer machineId4Day2, Integer machineId5Day2, String job1Day3, String job2Day3, String job3Day3, String job4Day3, String job5Day3, Integer machineId1Day3, Integer machineId2Day3, Integer machineId3Day3, Integer machineId4Day3, Integer machineId5Day3, String job1Day4, String job2Day4, String job3Day4, String job4Day4, String job5Day4, Integer machineId1Day4, Integer machineId2Day4, Integer machineId3Day4, Integer machineId4Day4, Integer machineId5Day4, String job1Day5, String job2Day5, String job3Day5, String job4Day5, String job5Day5, Integer machineId1Day5, Integer machineId2Day5, Integer machineId3Day5, Integer machineId4Day5, Integer machineId5Day5, String job1Day6, String job2Day6, String job3Day6, String job4Day6, String job5Day6, Integer machineId1Day6, Integer machineId2Day6, Integer machineId3Day6, Integer machineId4Day6, Integer machineId5Day6, String job1Day7, String job2Day7, String job3Day7, String job4Day7, String job5Day7, Integer machineId1Day7, Integer machineId2Day7, Integer machineId3Day7, Integer machineId4Day7, Integer machineId5Day7) {
        super(connection, "xjobcard", "xjobcard_id");
        setNew(xjobcardId.intValue() <= 0);
//        if (xjobcardId.intValue() != 0) {
            this.xjobcardId = xjobcardId;
//        }
        this.xemployeeId = xemployeeId;
        this.carddate = carddate;
        this.weekEnding = weekEnding;
        this.job1Day1 = job1Day1;
        this.job2Day1 = job2Day1;
        this.job3Day1 = job3Day1;
        this.job4Day1 = job4Day1;
        this.job5Day1 = job5Day1;
        this.machineId1Day1 = machineId1Day1;
        this.machineId2Day1 = machineId2Day1;
        this.machineId3Day1 = machineId3Day1;
        this.machineId4Day1 = machineId4Day1;
        this.machineId5Day1 = machineId5Day1;
        this.job1Day2 = job1Day2;
        this.job2Day2 = job2Day2;
        this.job3Day2 = job3Day2;
        this.job4Day2 = job4Day2;
        this.job5Day2 = job5Day2;
        this.machineId1Day2 = machineId1Day2;
        this.machineId2Day2 = machineId2Day2;
        this.machineId3Day2 = machineId3Day2;
        this.machineId4Day2 = machineId4Day2;
        this.machineId5Day2 = machineId5Day2;
        this.job1Day3 = job1Day3;
        this.job2Day3 = job2Day3;
        this.job3Day3 = job3Day3;
        this.job4Day3 = job4Day3;
        this.job5Day3 = job5Day3;
        this.machineId1Day3 = machineId1Day3;
        this.machineId2Day3 = machineId2Day3;
        this.machineId3Day3 = machineId3Day3;
        this.machineId4Day3 = machineId4Day3;
        this.machineId5Day3 = machineId5Day3;
        this.job1Day4 = job1Day4;
        this.job2Day4 = job2Day4;
        this.job3Day4 = job3Day4;
        this.job4Day4 = job4Day4;
        this.job5Day4 = job5Day4;
        this.machineId1Day4 = machineId1Day4;
        this.machineId2Day4 = machineId2Day4;
        this.machineId3Day4 = machineId3Day4;
        this.machineId4Day4 = machineId4Day4;
        this.machineId5Day4 = machineId5Day4;
        this.job1Day5 = job1Day5;
        this.job2Day5 = job2Day5;
        this.job3Day5 = job3Day5;
        this.job4Day5 = job4Day5;
        this.job5Day5 = job5Day5;
        this.machineId1Day5 = machineId1Day5;
        this.machineId2Day5 = machineId2Day5;
        this.machineId3Day5 = machineId3Day5;
        this.machineId4Day5 = machineId4Day5;
        this.machineId5Day5 = machineId5Day5;
        this.job1Day6 = job1Day6;
        this.job2Day6 = job2Day6;
        this.job3Day6 = job3Day6;
        this.job4Day6 = job4Day6;
        this.job5Day6 = job5Day6;
        this.machineId1Day6 = machineId1Day6;
        this.machineId2Day6 = machineId2Day6;
        this.machineId3Day6 = machineId3Day6;
        this.machineId4Day6 = machineId4Day6;
        this.machineId5Day6 = machineId5Day6;
        this.job1Day7 = job1Day7;
        this.job2Day7 = job2Day7;
        this.job3Day7 = job3Day7;
        this.job4Day7 = job4Day7;
        this.job5Day7 = job5Day7;
        this.machineId1Day7 = machineId1Day7;
        this.machineId2Day7 = machineId2Day7;
        this.machineId3Day7 = machineId3Day7;
        this.machineId4Day7 = machineId4Day7;
        this.machineId5Day7 = machineId5Day7;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Xjobcard xjobcard = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xjobcard_id,xemployee_id,carddate,week_ending,job1_day1,job2_day1,job3_day1,job4_day1,job5_day1,machine_id1_day1,machine_id2_day1,machine_id3_day1,machine_id4_day1,machine_id5_day1,job1_day2,job2_day2,job3_day2,job4_day2,job5_day2,machine_id1_day2,machine_id2_day2,machine_id3_day2,machine_id4_day2,machine_id5_day2,job1_day3,job2_day3,job3_day3,job4_day3,job5_day3,machine_id1_day3,machine_id2_day3,machine_id3_day3,machine_id4_day3,machine_id5_day3,job1_day4,job2_day4,job3_day4,job4_day4,job5_day4,machine_id1_day4,machine_id2_day4,machine_id3_day4,machine_id4_day4,machine_id5_day4,job1_day5,job2_day5,job3_day5,job4_day5,job5_day5,machine_id1_day5,machine_id2_day5,machine_id3_day5,machine_id4_day5,machine_id5_day5,job1_day6,job2_day6,job3_day6,job4_day6,job5_day6,machine_id1_day6,machine_id2_day6,machine_id3_day6,machine_id4_day6,machine_id5_day6,job1_day7,job2_day7,job3_day7,job4_day7,job5_day7,machine_id1_day7,machine_id2_day7,machine_id3_day7,machine_id4_day7,machine_id5_day7 FROM xjobcard WHERE xjobcard_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                xjobcard = new Xjobcard(getConnection());
                xjobcard.setXjobcardId(new Integer(rs.getInt(1)));
                xjobcard.setXemployeeId(new Integer(rs.getInt(2)));
                xjobcard.setCarddate(rs.getDate(3));
                xjobcard.setWeekEnding(rs.getDate(4));
                xjobcard.setJob1Day1(rs.getString(5));
                xjobcard.setJob2Day1(rs.getString(6));
                xjobcard.setJob3Day1(rs.getString(7));
                xjobcard.setJob4Day1(rs.getString(8));
                xjobcard.setJob5Day1(rs.getString(9));
                xjobcard.setMachineId1Day1(new Integer(rs.getInt(10)));
                xjobcard.setMachineId2Day1(new Integer(rs.getInt(11)));
                xjobcard.setMachineId3Day1(new Integer(rs.getInt(12)));
                xjobcard.setMachineId4Day1(new Integer(rs.getInt(13)));
                xjobcard.setMachineId5Day1(new Integer(rs.getInt(14)));
                xjobcard.setJob1Day2(rs.getString(15));
                xjobcard.setJob2Day2(rs.getString(16));
                xjobcard.setJob3Day2(rs.getString(17));
                xjobcard.setJob4Day2(rs.getString(18));
                xjobcard.setJob5Day2(rs.getString(19));
                xjobcard.setMachineId1Day2(new Integer(rs.getInt(20)));
                xjobcard.setMachineId2Day2(new Integer(rs.getInt(21)));
                xjobcard.setMachineId3Day2(new Integer(rs.getInt(22)));
                xjobcard.setMachineId4Day2(new Integer(rs.getInt(23)));
                xjobcard.setMachineId5Day2(new Integer(rs.getInt(24)));
                xjobcard.setJob1Day3(rs.getString(25));
                xjobcard.setJob2Day3(rs.getString(26));
                xjobcard.setJob3Day3(rs.getString(27));
                xjobcard.setJob4Day3(rs.getString(28));
                xjobcard.setJob5Day3(rs.getString(29));
                xjobcard.setMachineId1Day3(new Integer(rs.getInt(30)));
                xjobcard.setMachineId2Day3(new Integer(rs.getInt(31)));
                xjobcard.setMachineId3Day3(new Integer(rs.getInt(32)));
                xjobcard.setMachineId4Day3(new Integer(rs.getInt(33)));
                xjobcard.setMachineId5Day3(new Integer(rs.getInt(34)));
                xjobcard.setJob1Day4(rs.getString(35));
                xjobcard.setJob2Day4(rs.getString(36));
                xjobcard.setJob3Day4(rs.getString(37));
                xjobcard.setJob4Day4(rs.getString(38));
                xjobcard.setJob5Day4(rs.getString(39));
                xjobcard.setMachineId1Day4(new Integer(rs.getInt(40)));
                xjobcard.setMachineId2Day4(new Integer(rs.getInt(41)));
                xjobcard.setMachineId3Day4(new Integer(rs.getInt(42)));
                xjobcard.setMachineId4Day4(new Integer(rs.getInt(43)));
                xjobcard.setMachineId5Day4(new Integer(rs.getInt(44)));
                xjobcard.setJob1Day5(rs.getString(45));
                xjobcard.setJob2Day5(rs.getString(46));
                xjobcard.setJob3Day5(rs.getString(47));
                xjobcard.setJob4Day5(rs.getString(48));
                xjobcard.setJob5Day5(rs.getString(49));
                xjobcard.setMachineId1Day5(new Integer(rs.getInt(50)));
                xjobcard.setMachineId2Day5(new Integer(rs.getInt(51)));
                xjobcard.setMachineId3Day5(new Integer(rs.getInt(52)));
                xjobcard.setMachineId4Day5(new Integer(rs.getInt(53)));
                xjobcard.setMachineId5Day5(new Integer(rs.getInt(54)));
                xjobcard.setJob1Day6(rs.getString(55));
                xjobcard.setJob2Day6(rs.getString(56));
                xjobcard.setJob3Day6(rs.getString(57));
                xjobcard.setJob4Day6(rs.getString(58));
                xjobcard.setJob5Day6(rs.getString(59));
                xjobcard.setMachineId1Day6(new Integer(rs.getInt(60)));
                xjobcard.setMachineId2Day6(new Integer(rs.getInt(61)));
                xjobcard.setMachineId3Day6(new Integer(rs.getInt(62)));
                xjobcard.setMachineId4Day6(new Integer(rs.getInt(63)));
                xjobcard.setMachineId5Day6(new Integer(rs.getInt(64)));
                xjobcard.setJob1Day7(rs.getString(65));
                xjobcard.setJob2Day7(rs.getString(66));
                xjobcard.setJob3Day7(rs.getString(67));
                xjobcard.setJob4Day7(rs.getString(68));
                xjobcard.setJob5Day7(rs.getString(69));
                xjobcard.setMachineId1Day7(new Integer(rs.getInt(70)));
                xjobcard.setMachineId2Day7(new Integer(rs.getInt(71)));
                xjobcard.setMachineId3Day7(new Integer(rs.getInt(72)));
                xjobcard.setMachineId4Day7(new Integer(rs.getInt(73)));
                xjobcard.setMachineId5Day7(new Integer(rs.getInt(74)));
                xjobcard.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return xjobcard;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO xjobcard ("+(getXjobcardId().intValue()!=0?"xjobcard_id,":"")+"xemployee_id,carddate,week_ending,job1_day1,job2_day1,job3_day1,job4_day1,job5_day1,machine_id1_day1,machine_id2_day1,machine_id3_day1,machine_id4_day1,machine_id5_day1,job1_day2,job2_day2,job3_day2,job4_day2,job5_day2,machine_id1_day2,machine_id2_day2,machine_id3_day2,machine_id4_day2,machine_id5_day2,job1_day3,job2_day3,job3_day3,job4_day3,job5_day3,machine_id1_day3,machine_id2_day3,machine_id3_day3,machine_id4_day3,machine_id5_day3,job1_day4,job2_day4,job3_day4,job4_day4,job5_day4,machine_id1_day4,machine_id2_day4,machine_id3_day4,machine_id4_day4,machine_id5_day4,job1_day5,job2_day5,job3_day5,job4_day5,job5_day5,machine_id1_day5,machine_id2_day5,machine_id3_day5,machine_id4_day5,machine_id5_day5,job1_day6,job2_day6,job3_day6,job4_day6,job5_day6,machine_id1_day6,machine_id2_day6,machine_id3_day6,machine_id4_day6,machine_id5_day6,job1_day7,job2_day7,job3_day7,job4_day7,job5_day7,machine_id1_day7,machine_id2_day7,machine_id3_day7,machine_id4_day7,machine_id5_day7) values("+(getXjobcardId().intValue()!=0?"?,":"")+"?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getXjobcardId().intValue()!=0) {
                 ps.setObject(++n, getXjobcardId());
             }
             ps.setObject(++n, getXemployeeId());
             ps.setObject(++n, getCarddate());
             ps.setObject(++n, getWeekEnding());
             ps.setObject(++n, getJob1Day1());
             ps.setObject(++n, getJob2Day1());
             ps.setObject(++n, getJob3Day1());
             ps.setObject(++n, getJob4Day1());
             ps.setObject(++n, getJob5Day1());
             ps.setObject(++n, getMachineId1Day1());
             ps.setObject(++n, getMachineId2Day1());
             ps.setObject(++n, getMachineId3Day1());
             ps.setObject(++n, getMachineId4Day1());
             ps.setObject(++n, getMachineId5Day1());
             ps.setObject(++n, getJob1Day2());
             ps.setObject(++n, getJob2Day2());
             ps.setObject(++n, getJob3Day2());
             ps.setObject(++n, getJob4Day2());
             ps.setObject(++n, getJob5Day2());
             ps.setObject(++n, getMachineId1Day2());
             ps.setObject(++n, getMachineId2Day2());
             ps.setObject(++n, getMachineId3Day2());
             ps.setObject(++n, getMachineId4Day2());
             ps.setObject(++n, getMachineId5Day2());
             ps.setObject(++n, getJob1Day3());
             ps.setObject(++n, getJob2Day3());
             ps.setObject(++n, getJob3Day3());
             ps.setObject(++n, getJob4Day3());
             ps.setObject(++n, getJob5Day3());
             ps.setObject(++n, getMachineId1Day3());
             ps.setObject(++n, getMachineId2Day3());
             ps.setObject(++n, getMachineId3Day3());
             ps.setObject(++n, getMachineId4Day3());
             ps.setObject(++n, getMachineId5Day3());
             ps.setObject(++n, getJob1Day4());
             ps.setObject(++n, getJob2Day4());
             ps.setObject(++n, getJob3Day4());
             ps.setObject(++n, getJob4Day4());
             ps.setObject(++n, getJob5Day4());
             ps.setObject(++n, getMachineId1Day4());
             ps.setObject(++n, getMachineId2Day4());
             ps.setObject(++n, getMachineId3Day4());
             ps.setObject(++n, getMachineId4Day4());
             ps.setObject(++n, getMachineId5Day4());
             ps.setObject(++n, getJob1Day5());
             ps.setObject(++n, getJob2Day5());
             ps.setObject(++n, getJob3Day5());
             ps.setObject(++n, getJob4Day5());
             ps.setObject(++n, getJob5Day5());
             ps.setObject(++n, getMachineId1Day5());
             ps.setObject(++n, getMachineId2Day5());
             ps.setObject(++n, getMachineId3Day5());
             ps.setObject(++n, getMachineId4Day5());
             ps.setObject(++n, getMachineId5Day5());
             ps.setObject(++n, getJob1Day6());
             ps.setObject(++n, getJob2Day6());
             ps.setObject(++n, getJob3Day6());
             ps.setObject(++n, getJob4Day6());
             ps.setObject(++n, getJob5Day6());
             ps.setObject(++n, getMachineId1Day6());
             ps.setObject(++n, getMachineId2Day6());
             ps.setObject(++n, getMachineId3Day6());
             ps.setObject(++n, getMachineId4Day6());
             ps.setObject(++n, getMachineId5Day6());
             ps.setObject(++n, getJob1Day7());
             ps.setObject(++n, getJob2Day7());
             ps.setObject(++n, getJob3Day7());
             ps.setObject(++n, getJob4Day7());
             ps.setObject(++n, getJob5Day7());
             ps.setObject(++n, getMachineId1Day7());
             ps.setObject(++n, getMachineId2Day7());
             ps.setObject(++n, getMachineId3Day7());
             ps.setObject(++n, getMachineId4Day7());
             ps.setObject(++n, getMachineId5Day7());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getXjobcardId().intValue()==0) {
             stmt = "SELECT max(xjobcard_id) FROM xjobcard";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setXjobcardId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE xjobcard " +
                    "SET xemployee_id = ?, carddate = ?, week_ending = ?, job1_day1 = ?, job2_day1 = ?, job3_day1 = ?, job4_day1 = ?, job5_day1 = ?, machine_id1_day1 = ?, machine_id2_day1 = ?, machine_id3_day1 = ?, machine_id4_day1 = ?, machine_id5_day1 = ?, job1_day2 = ?, job2_day2 = ?, job3_day2 = ?, job4_day2 = ?, job5_day2 = ?, machine_id1_day2 = ?, machine_id2_day2 = ?, machine_id3_day2 = ?, machine_id4_day2 = ?, machine_id5_day2 = ?, job1_day3 = ?, job2_day3 = ?, job3_day3 = ?, job4_day3 = ?, job5_day3 = ?, machine_id1_day3 = ?, machine_id2_day3 = ?, machine_id3_day3 = ?, machine_id4_day3 = ?, machine_id5_day3 = ?, job1_day4 = ?, job2_day4 = ?, job3_day4 = ?, job4_day4 = ?, job5_day4 = ?, machine_id1_day4 = ?, machine_id2_day4 = ?, machine_id3_day4 = ?, machine_id4_day4 = ?, machine_id5_day4 = ?, job1_day5 = ?, job2_day5 = ?, job3_day5 = ?, job4_day5 = ?, job5_day5 = ?, machine_id1_day5 = ?, machine_id2_day5 = ?, machine_id3_day5 = ?, machine_id4_day5 = ?, machine_id5_day5 = ?, job1_day6 = ?, job2_day6 = ?, job3_day6 = ?, job4_day6 = ?, job5_day6 = ?, machine_id1_day6 = ?, machine_id2_day6 = ?, machine_id3_day6 = ?, machine_id4_day6 = ?, machine_id5_day6 = ?, job1_day7 = ?, job2_day7 = ?, job3_day7 = ?, job4_day7 = ?, job5_day7 = ?, machine_id1_day7 = ?, machine_id2_day7 = ?, machine_id3_day7 = ?, machine_id4_day7 = ?, machine_id5_day7 = ?" + 
                    " WHERE xjobcard_id = " + getXjobcardId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getXemployeeId());
                ps.setObject(2, getCarddate());
                ps.setObject(3, getWeekEnding());
                ps.setObject(4, getJob1Day1());
                ps.setObject(5, getJob2Day1());
                ps.setObject(6, getJob3Day1());
                ps.setObject(7, getJob4Day1());
                ps.setObject(8, getJob5Day1());
                ps.setObject(9, getMachineId1Day1());
                ps.setObject(10, getMachineId2Day1());
                ps.setObject(11, getMachineId3Day1());
                ps.setObject(12, getMachineId4Day1());
                ps.setObject(13, getMachineId5Day1());
                ps.setObject(14, getJob1Day2());
                ps.setObject(15, getJob2Day2());
                ps.setObject(16, getJob3Day2());
                ps.setObject(17, getJob4Day2());
                ps.setObject(18, getJob5Day2());
                ps.setObject(19, getMachineId1Day2());
                ps.setObject(20, getMachineId2Day2());
                ps.setObject(21, getMachineId3Day2());
                ps.setObject(22, getMachineId4Day2());
                ps.setObject(23, getMachineId5Day2());
                ps.setObject(24, getJob1Day3());
                ps.setObject(25, getJob2Day3());
                ps.setObject(26, getJob3Day3());
                ps.setObject(27, getJob4Day3());
                ps.setObject(28, getJob5Day3());
                ps.setObject(29, getMachineId1Day3());
                ps.setObject(30, getMachineId2Day3());
                ps.setObject(31, getMachineId3Day3());
                ps.setObject(32, getMachineId4Day3());
                ps.setObject(33, getMachineId5Day3());
                ps.setObject(34, getJob1Day4());
                ps.setObject(35, getJob2Day4());
                ps.setObject(36, getJob3Day4());
                ps.setObject(37, getJob4Day4());
                ps.setObject(38, getJob5Day4());
                ps.setObject(39, getMachineId1Day4());
                ps.setObject(40, getMachineId2Day4());
                ps.setObject(41, getMachineId3Day4());
                ps.setObject(42, getMachineId4Day4());
                ps.setObject(43, getMachineId5Day4());
                ps.setObject(44, getJob1Day5());
                ps.setObject(45, getJob2Day5());
                ps.setObject(46, getJob3Day5());
                ps.setObject(47, getJob4Day5());
                ps.setObject(48, getJob5Day5());
                ps.setObject(49, getMachineId1Day5());
                ps.setObject(50, getMachineId2Day5());
                ps.setObject(51, getMachineId3Day5());
                ps.setObject(52, getMachineId4Day5());
                ps.setObject(53, getMachineId5Day5());
                ps.setObject(54, getJob1Day6());
                ps.setObject(55, getJob2Day6());
                ps.setObject(56, getJob3Day6());
                ps.setObject(57, getJob4Day6());
                ps.setObject(58, getJob5Day6());
                ps.setObject(59, getMachineId1Day6());
                ps.setObject(60, getMachineId2Day6());
                ps.setObject(61, getMachineId3Day6());
                ps.setObject(62, getMachineId4Day6());
                ps.setObject(63, getMachineId5Day6());
                ps.setObject(64, getJob1Day7());
                ps.setObject(65, getJob2Day7());
                ps.setObject(66, getJob3Day7());
                ps.setObject(67, getJob4Day7());
                ps.setObject(68, getJob5Day7());
                ps.setObject(69, getMachineId1Day7());
                ps.setObject(70, getMachineId2Day7());
                ps.setObject(71, getMachineId3Day7());
                ps.setObject(72, getMachineId4Day7());
                ps.setObject(73, getMachineId5Day7());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM xjobcard " +
                "WHERE xjobcard_id = " + getXjobcardId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setXjobcardId(new Integer(-getXjobcardId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getXjobcardId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xjobcard_id,xemployee_id,carddate,week_ending,job1_day1,job2_day1,job3_day1,job4_day1,job5_day1,machine_id1_day1,machine_id2_day1,machine_id3_day1,machine_id4_day1,machine_id5_day1,job1_day2,job2_day2,job3_day2,job4_day2,job5_day2,machine_id1_day2,machine_id2_day2,machine_id3_day2,machine_id4_day2,machine_id5_day2,job1_day3,job2_day3,job3_day3,job4_day3,job5_day3,machine_id1_day3,machine_id2_day3,machine_id3_day3,machine_id4_day3,machine_id5_day3,job1_day4,job2_day4,job3_day4,job4_day4,job5_day4,machine_id1_day4,machine_id2_day4,machine_id3_day4,machine_id4_day4,machine_id5_day4,job1_day5,job2_day5,job3_day5,job4_day5,job5_day5,machine_id1_day5,machine_id2_day5,machine_id3_day5,machine_id4_day5,machine_id5_day5,job1_day6,job2_day6,job3_day6,job4_day6,job5_day6,machine_id1_day6,machine_id2_day6,machine_id3_day6,machine_id4_day6,machine_id5_day6,job1_day7,job2_day7,job3_day7,job4_day7,job5_day7,machine_id1_day7,machine_id2_day7,machine_id3_day7,machine_id4_day7,machine_id5_day7 FROM xjobcard " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Xjobcard(con,new Integer(rs.getInt(1)),new Integer(rs.getInt(2)),rs.getDate(3),rs.getDate(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),new Integer(rs.getInt(10)),new Integer(rs.getInt(11)),new Integer(rs.getInt(12)),new Integer(rs.getInt(13)),new Integer(rs.getInt(14)),rs.getString(15),rs.getString(16),rs.getString(17),rs.getString(18),rs.getString(19),new Integer(rs.getInt(20)),new Integer(rs.getInt(21)),new Integer(rs.getInt(22)),new Integer(rs.getInt(23)),new Integer(rs.getInt(24)),rs.getString(25),rs.getString(26),rs.getString(27),rs.getString(28),rs.getString(29),new Integer(rs.getInt(30)),new Integer(rs.getInt(31)),new Integer(rs.getInt(32)),new Integer(rs.getInt(33)),new Integer(rs.getInt(34)),rs.getString(35),rs.getString(36),rs.getString(37),rs.getString(38),rs.getString(39),new Integer(rs.getInt(40)),new Integer(rs.getInt(41)),new Integer(rs.getInt(42)),new Integer(rs.getInt(43)),new Integer(rs.getInt(44)),rs.getString(45),rs.getString(46),rs.getString(47),rs.getString(48),rs.getString(49),new Integer(rs.getInt(50)),new Integer(rs.getInt(51)),new Integer(rs.getInt(52)),new Integer(rs.getInt(53)),new Integer(rs.getInt(54)),rs.getString(55),rs.getString(56),rs.getString(57),rs.getString(58),rs.getString(59),new Integer(rs.getInt(60)),new Integer(rs.getInt(61)),new Integer(rs.getInt(62)),new Integer(rs.getInt(63)),new Integer(rs.getInt(64)),rs.getString(65),rs.getString(66),rs.getString(67),rs.getString(68),rs.getString(69),new Integer(rs.getInt(70)),new Integer(rs.getInt(71)),new Integer(rs.getInt(72)),new Integer(rs.getInt(73)),new Integer(rs.getInt(74))));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Xjobcard[] objects = new Xjobcard[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Xjobcard xjobcard = (Xjobcard) lst.get(i);
            objects[i] = xjobcard;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xjobcard_id FROM xjobcard " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getXjobcardId() + getDelimiter();
    //}

    public Integer getXjobcardId() {
        return xjobcardId;
    }

    public void setXjobcardId(Integer xjobcardId) throws ForeignKeyViolationException {
        setWasChanged(this.xjobcardId != null && this.xjobcardId != xjobcardId);
        this.xjobcardId = xjobcardId;
        setNew(xjobcardId.intValue() == 0);
    }

    public Integer getXemployeeId() {
        return xemployeeId;
    }

    public void setXemployeeId(Integer xemployeeId) throws SQLException, ForeignKeyViolationException {
        if (xemployeeId!=null && !Xemployee.exists(getConnection(),"xemployee_id = " + xemployeeId)) {
            throw new ForeignKeyViolationException("Can't set xemployee_id, foreign key violation: xjobcard_xemployee_fk");
        }
        setWasChanged(this.xemployeeId != null && !this.xemployeeId.equals(xemployeeId));
        this.xemployeeId = xemployeeId;
    }

    public Date getCarddate() {
        return carddate;
    }

    public void setCarddate(Date carddate) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.carddate != null && !this.carddate.equals(carddate));
        this.carddate = carddate;
    }

    public Date getWeekEnding() {
        return weekEnding;
    }

    public void setWeekEnding(Date weekEnding) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.weekEnding != null && !this.weekEnding.equals(weekEnding));
        this.weekEnding = weekEnding;
    }

    public String getJob1Day1() {
        return job1Day1;
    }

    public void setJob1Day1(String job1Day1) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day1 != null && !this.job1Day1.equals(job1Day1));
        this.job1Day1 = job1Day1;
    }

    public String getJob2Day1() {
        return job2Day1;
    }

    public void setJob2Day1(String job2Day1) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day1 != null && !this.job2Day1.equals(job2Day1));
        this.job2Day1 = job2Day1;
    }

    public String getJob3Day1() {
        return job3Day1;
    }

    public void setJob3Day1(String job3Day1) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day1 != null && !this.job3Day1.equals(job3Day1));
        this.job3Day1 = job3Day1;
    }

    public String getJob4Day1() {
        return job4Day1;
    }

    public void setJob4Day1(String job4Day1) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day1 != null && !this.job4Day1.equals(job4Day1));
        this.job4Day1 = job4Day1;
    }

    public String getJob5Day1() {
        return job5Day1;
    }

    public void setJob5Day1(String job5Day1) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day1 != null && !this.job5Day1.equals(job5Day1));
        this.job5Day1 = job5Day1;
    }

    public Integer getMachineId1Day1() {
        return machineId1Day1;
    }

    public void setMachineId1Day1(Integer machineId1Day1) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day1)
            machineId1Day1 = machineId1Day1 == 0 ? null : machineId1Day1;
        if (machineId1Day1!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day1)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day1, foreign key violation: xjobcard_xmachine_fk11");
        }
        setWasChanged(this.machineId1Day1 != null && !this.machineId1Day1.equals(machineId1Day1));
        this.machineId1Day1 = machineId1Day1;
    }

    public Integer getMachineId2Day1() {
        return machineId2Day1;
    }

    public void setMachineId2Day1(Integer machineId2Day1) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day1)
            machineId2Day1 = machineId2Day1 == 0 ? null : machineId2Day1;
        if (machineId2Day1!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day1)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day1, foreign key violation: xjobcard_xmachine_fk21");
        }
        setWasChanged(this.machineId2Day1 != null && !this.machineId2Day1.equals(machineId2Day1));
        this.machineId2Day1 = machineId2Day1;
    }

    public Integer getMachineId3Day1() {
        return machineId3Day1;
    }

    public void setMachineId3Day1(Integer machineId3Day1) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day1)
            machineId3Day1 = machineId3Day1 == 0 ? null : machineId3Day1;
        if (machineId3Day1!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day1)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day1, foreign key violation: xjobcard_xmachine_fk31");
        }
        setWasChanged(this.machineId3Day1 != null && !this.machineId3Day1.equals(machineId3Day1));
        this.machineId3Day1 = machineId3Day1;
    }

    public Integer getMachineId4Day1() {
        return machineId4Day1;
    }

    public void setMachineId4Day1(Integer machineId4Day1) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day1)
            machineId4Day1 = machineId4Day1 == 0 ? null : machineId4Day1;
        if (machineId4Day1!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day1)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day1, foreign key violation: xjobcard_xmachine_fk41");
        }
        setWasChanged(this.machineId4Day1 != null && !this.machineId4Day1.equals(machineId4Day1));
        this.machineId4Day1 = machineId4Day1;
    }

    public Integer getMachineId5Day1() {
        return machineId5Day1;
    }

    public void setMachineId5Day1(Integer machineId5Day1) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day1)
            machineId5Day1 = machineId5Day1 == 0 ? null : machineId5Day1;
        if (machineId5Day1!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day1)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day1, foreign key violation: xjobcard_xmachine_fk51");
        }
        setWasChanged(this.machineId5Day1 != null && !this.machineId5Day1.equals(machineId5Day1));
        this.machineId5Day1 = machineId5Day1;
    }

    public String getJob1Day2() {
        return job1Day2;
    }

    public void setJob1Day2(String job1Day2) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day2 != null && !this.job1Day2.equals(job1Day2));
        this.job1Day2 = job1Day2;
    }

    public String getJob2Day2() {
        return job2Day2;
    }

    public void setJob2Day2(String job2Day2) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day2 != null && !this.job2Day2.equals(job2Day2));
        this.job2Day2 = job2Day2;
    }

    public String getJob3Day2() {
        return job3Day2;
    }

    public void setJob3Day2(String job3Day2) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day2 != null && !this.job3Day2.equals(job3Day2));
        this.job3Day2 = job3Day2;
    }

    public String getJob4Day2() {
        return job4Day2;
    }

    public void setJob4Day2(String job4Day2) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day2 != null && !this.job4Day2.equals(job4Day2));
        this.job4Day2 = job4Day2;
    }

    public String getJob5Day2() {
        return job5Day2;
    }

    public void setJob5Day2(String job5Day2) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day2 != null && !this.job5Day2.equals(job5Day2));
        this.job5Day2 = job5Day2;
    }

    public Integer getMachineId1Day2() {
        return machineId1Day2;
    }

    public void setMachineId1Day2(Integer machineId1Day2) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day2)
            machineId1Day2 = machineId1Day2 == 0 ? null : machineId1Day2;
        if (machineId1Day2!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day2)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day2, foreign key violation: xjobcard_xmachine_fk12");
        }
        setWasChanged(this.machineId1Day2 != null && !this.machineId1Day2.equals(machineId1Day2));
        this.machineId1Day2 = machineId1Day2;
    }

    public Integer getMachineId2Day2() {
        return machineId2Day2;
    }

    public void setMachineId2Day2(Integer machineId2Day2) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day2)
            machineId2Day2 = machineId2Day2 == 0 ? null : machineId2Day2;
        if (machineId2Day2!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day2)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day2, foreign key violation: xjobcard_xmachine_fk22");
        }
        setWasChanged(this.machineId2Day2 != null && !this.machineId2Day2.equals(machineId2Day2));
        this.machineId2Day2 = machineId2Day2;
    }

    public Integer getMachineId3Day2() {
        return machineId3Day2;
    }

    public void setMachineId3Day2(Integer machineId3Day2) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day2)
            machineId3Day2 = machineId3Day2 == 0 ? null : machineId3Day2;
        if (machineId3Day2!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day2)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day2, foreign key violation: xjobcard_xmachine_fk32");
        }
        setWasChanged(this.machineId3Day2 != null && !this.machineId3Day2.equals(machineId3Day2));
        this.machineId3Day2 = machineId3Day2;
    }

    public Integer getMachineId4Day2() {
        return machineId4Day2;
    }

    public void setMachineId4Day2(Integer machineId4Day2) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day2)
            machineId4Day2 = machineId4Day2 == 0 ? null : machineId4Day2;
        if (machineId4Day2!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day2)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day2, foreign key violation: xjobcard_xmachine_fk42");
        }
        setWasChanged(this.machineId4Day2 != null && !this.machineId4Day2.equals(machineId4Day2));
        this.machineId4Day2 = machineId4Day2;
    }

    public Integer getMachineId5Day2() {
        return machineId5Day2;
    }

    public void setMachineId5Day2(Integer machineId5Day2) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day2)
            machineId5Day2 = machineId5Day2 == 0 ? null : machineId5Day2;
        if (machineId5Day2!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day2)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day2, foreign key violation: xjobcard_xmachine_fk52");
        }
        setWasChanged(this.machineId5Day2 != null && !this.machineId5Day2.equals(machineId5Day2));
        this.machineId5Day2 = machineId5Day2;
    }

    public String getJob1Day3() {
        return job1Day3;
    }

    public void setJob1Day3(String job1Day3) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day3 != null && !this.job1Day3.equals(job1Day3));
        this.job1Day3 = job1Day3;
    }

    public String getJob2Day3() {
        return job2Day3;
    }

    public void setJob2Day3(String job2Day3) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day3 != null && !this.job2Day3.equals(job2Day3));
        this.job2Day3 = job2Day3;
    }

    public String getJob3Day3() {
        return job3Day3;
    }

    public void setJob3Day3(String job3Day3) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day3 != null && !this.job3Day3.equals(job3Day3));
        this.job3Day3 = job3Day3;
    }

    public String getJob4Day3() {
        return job4Day3;
    }

    public void setJob4Day3(String job4Day3) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day3 != null && !this.job4Day3.equals(job4Day3));
        this.job4Day3 = job4Day3;
    }

    public String getJob5Day3() {
        return job5Day3;
    }

    public void setJob5Day3(String job5Day3) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day3 != null && !this.job5Day3.equals(job5Day3));
        this.job5Day3 = job5Day3;
    }

    public Integer getMachineId1Day3() {
        return machineId1Day3;
    }

    public void setMachineId1Day3(Integer machineId1Day3) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day3)
            machineId1Day3 = machineId1Day3 == 0 ? null : machineId1Day3;
        if (machineId1Day3!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day3)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day3, foreign key violation: xjobcard_xmachine_fk13");
        }
        setWasChanged(this.machineId1Day3 != null && !this.machineId1Day3.equals(machineId1Day3));
        this.machineId1Day3 = machineId1Day3;
    }

    public Integer getMachineId2Day3() {
        return machineId2Day3;
    }

    public void setMachineId2Day3(Integer machineId2Day3) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day3)
            machineId2Day3 = machineId2Day3 == 0 ? null : machineId2Day3;
        if (machineId2Day3!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day3)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day3, foreign key violation: xjobcard_xmachine_fk23");
        }
        setWasChanged(this.machineId2Day3 != null && !this.machineId2Day3.equals(machineId2Day3));
        this.machineId2Day3 = machineId2Day3;
    }

    public Integer getMachineId3Day3() {
        return machineId3Day3;
    }

    public void setMachineId3Day3(Integer machineId3Day3) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day3)
            machineId3Day3 = machineId3Day3 == 0 ? null : machineId3Day3;
        if (machineId3Day3!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day3)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day3, foreign key violation: xjobcard_xmachine_fk33");
        }
        setWasChanged(this.machineId3Day3 != null && !this.machineId3Day3.equals(machineId3Day3));
        this.machineId3Day3 = machineId3Day3;
    }

    public Integer getMachineId4Day3() {
        return machineId4Day3;
    }

    public void setMachineId4Day3(Integer machineId4Day3) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day3)
            machineId4Day3 = machineId4Day3 == 0 ? null : machineId4Day3;
        if (machineId4Day3!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day3)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day3, foreign key violation: xjobcard_xmachine_fk43");
        }
        setWasChanged(this.machineId4Day3 != null && !this.machineId4Day3.equals(machineId4Day3));
        this.machineId4Day3 = machineId4Day3;
    }

    public Integer getMachineId5Day3() {
        return machineId5Day3;
    }

    public void setMachineId5Day3(Integer machineId5Day3) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day3)
            machineId5Day3 = machineId5Day3 == 0 ? null : machineId5Day3;
        if (machineId5Day3!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day3)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day3, foreign key violation: xjobcard_xmachine_fk53");
        }
        setWasChanged(this.machineId5Day3 != null && !this.machineId5Day3.equals(machineId5Day3));
        this.machineId5Day3 = machineId5Day3;
    }

    public String getJob1Day4() {
        return job1Day4;
    }

    public void setJob1Day4(String job1Day4) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day4 != null && !this.job1Day4.equals(job1Day4));
        this.job1Day4 = job1Day4;
    }

    public String getJob2Day4() {
        return job2Day4;
    }

    public void setJob2Day4(String job2Day4) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day4 != null && !this.job2Day4.equals(job2Day4));
        this.job2Day4 = job2Day4;
    }

    public String getJob3Day4() {
        return job3Day4;
    }

    public void setJob3Day4(String job3Day4) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day4 != null && !this.job3Day4.equals(job3Day4));
        this.job3Day4 = job3Day4;
    }

    public String getJob4Day4() {
        return job4Day4;
    }

    public void setJob4Day4(String job4Day4) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day4 != null && !this.job4Day4.equals(job4Day4));
        this.job4Day4 = job4Day4;
    }

    public String getJob5Day4() {
        return job5Day4;
    }

    public void setJob5Day4(String job5Day4) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day4 != null && !this.job5Day4.equals(job5Day4));
        this.job5Day4 = job5Day4;
    }

    public Integer getMachineId1Day4() {
        return machineId1Day4;
    }

    public void setMachineId1Day4(Integer machineId1Day4) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day4)
            machineId1Day4 = machineId1Day4 == 0 ? null : machineId1Day4;
        if (machineId1Day4!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day4)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day4, foreign key violation: xjobcard_xmachine_fk14");
        }
        setWasChanged(this.machineId1Day4 != null && !this.machineId1Day4.equals(machineId1Day4));
        this.machineId1Day4 = machineId1Day4;
    }

    public Integer getMachineId2Day4() {
        return machineId2Day4;
    }

    public void setMachineId2Day4(Integer machineId2Day4) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day4)
            machineId2Day4 = machineId2Day4 == 0 ? null : machineId2Day4;
        if (machineId2Day4!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day4)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day4, foreign key violation: xjobcard_xmachine_fk24");
        }
        setWasChanged(this.machineId2Day4 != null && !this.machineId2Day4.equals(machineId2Day4));
        this.machineId2Day4 = machineId2Day4;
    }

    public Integer getMachineId3Day4() {
        return machineId3Day4;
    }

    public void setMachineId3Day4(Integer machineId3Day4) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day4)
            machineId3Day4 = machineId3Day4 == 0 ? null : machineId3Day4;
        if (machineId3Day4!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day4)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day4, foreign key violation: xjobcard_xmachine_fk34");
        }
        setWasChanged(this.machineId3Day4 != null && !this.machineId3Day4.equals(machineId3Day4));
        this.machineId3Day4 = machineId3Day4;
    }

    public Integer getMachineId4Day4() {
        return machineId4Day4;
    }

    public void setMachineId4Day4(Integer machineId4Day4) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day4)
            machineId4Day4 = machineId4Day4 == 0 ? null : machineId4Day4;
        if (machineId4Day4!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day4)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day4, foreign key violation: xjobcard_xmachine_fk44");
        }
        setWasChanged(this.machineId4Day4 != null && !this.machineId4Day4.equals(machineId4Day4));
        this.machineId4Day4 = machineId4Day4;
    }

    public Integer getMachineId5Day4() {
        return machineId5Day4;
    }

    public void setMachineId5Day4(Integer machineId5Day4) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day4)
            machineId5Day4 = machineId5Day4 == 0 ? null : machineId5Day4;
        if (machineId5Day4!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day4)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day4, foreign key violation: xjobcard_xmachine_fk54");
        }
        setWasChanged(this.machineId5Day4 != null && !this.machineId5Day4.equals(machineId5Day4));
        this.machineId5Day4 = machineId5Day4;
    }

    public String getJob1Day5() {
        return job1Day5;
    }

    public void setJob1Day5(String job1Day5) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day5 != null && !this.job1Day5.equals(job1Day5));
        this.job1Day5 = job1Day5;
    }

    public String getJob2Day5() {
        return job2Day5;
    }

    public void setJob2Day5(String job2Day5) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day5 != null && !this.job2Day5.equals(job2Day5));
        this.job2Day5 = job2Day5;
    }

    public String getJob3Day5() {
        return job3Day5;
    }

    public void setJob3Day5(String job3Day5) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day5 != null && !this.job3Day5.equals(job3Day5));
        this.job3Day5 = job3Day5;
    }

    public String getJob4Day5() {
        return job4Day5;
    }

    public void setJob4Day5(String job4Day5) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day5 != null && !this.job4Day5.equals(job4Day5));
        this.job4Day5 = job4Day5;
    }

    public String getJob5Day5() {
        return job5Day5;
    }

    public void setJob5Day5(String job5Day5) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day5 != null && !this.job5Day5.equals(job5Day5));
        this.job5Day5 = job5Day5;
    }

    public Integer getMachineId1Day5() {
        return machineId1Day5;
    }

    public void setMachineId1Day5(Integer machineId1Day5) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day5)
            machineId1Day5 = machineId1Day5 == 0 ? null : machineId1Day5;
        if (machineId1Day5!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day5)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day5, foreign key violation: xjobcard_xmachine_fk15");
        }
        setWasChanged(this.machineId1Day5 != null && !this.machineId1Day5.equals(machineId1Day5));
        this.machineId1Day5 = machineId1Day5;
    }

    public Integer getMachineId2Day5() {
        return machineId2Day5;
    }

    public void setMachineId2Day5(Integer machineId2Day5) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day5)
            machineId2Day5 = machineId2Day5 == 0 ? null : machineId2Day5;
        if (machineId2Day5!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day5)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day5, foreign key violation: xjobcard_xmachine_fk25");
        }
        setWasChanged(this.machineId2Day5 != null && !this.machineId2Day5.equals(machineId2Day5));
        this.machineId2Day5 = machineId2Day5;
    }

    public Integer getMachineId3Day5() {
        return machineId3Day5;
    }

    public void setMachineId3Day5(Integer machineId3Day5) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day5)
            machineId3Day5 = machineId3Day5 == 0 ? null : machineId3Day5;
        if (machineId3Day5!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day5)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day5, foreign key violation: xjobcard_xmachine_fk35");
        }
        setWasChanged(this.machineId3Day5 != null && !this.machineId3Day5.equals(machineId3Day5));
        this.machineId3Day5 = machineId3Day5;
    }

    public Integer getMachineId4Day5() {
        return machineId4Day5;
    }

    public void setMachineId4Day5(Integer machineId4Day5) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day5)
            machineId4Day5 = machineId4Day5 == 0 ? null : machineId4Day5;
        if (machineId4Day5!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day5)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day5, foreign key violation: xjobcard_xmachine_fk45");
        }
        setWasChanged(this.machineId4Day5 != null && !this.machineId4Day5.equals(machineId4Day5));
        this.machineId4Day5 = machineId4Day5;
    }

    public Integer getMachineId5Day5() {
        return machineId5Day5;
    }

    public void setMachineId5Day5(Integer machineId5Day5) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day5)
            machineId5Day5 = machineId5Day5 == 0 ? null : machineId5Day5;
        if (machineId5Day5!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day5)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day5, foreign key violation: xjobcard_xmachine_fk55");
        }
        setWasChanged(this.machineId5Day5 != null && !this.machineId5Day5.equals(machineId5Day5));
        this.machineId5Day5 = machineId5Day5;
    }

    public String getJob1Day6() {
        return job1Day6;
    }

    public void setJob1Day6(String job1Day6) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day6 != null && !this.job1Day6.equals(job1Day6));
        this.job1Day6 = job1Day6;
    }

    public String getJob2Day6() {
        return job2Day6;
    }

    public void setJob2Day6(String job2Day6) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day6 != null && !this.job2Day6.equals(job2Day6));
        this.job2Day6 = job2Day6;
    }

    public String getJob3Day6() {
        return job3Day6;
    }

    public void setJob3Day6(String job3Day6) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day6 != null && !this.job3Day6.equals(job3Day6));
        this.job3Day6 = job3Day6;
    }

    public String getJob4Day6() {
        return job4Day6;
    }

    public void setJob4Day6(String job4Day6) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day6 != null && !this.job4Day6.equals(job4Day6));
        this.job4Day6 = job4Day6;
    }

    public String getJob5Day6() {
        return job5Day6;
    }

    public void setJob5Day6(String job5Day6) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day6 != null && !this.job5Day6.equals(job5Day6));
        this.job5Day6 = job5Day6;
    }

    public Integer getMachineId1Day6() {
        return machineId1Day6;
    }

    public void setMachineId1Day6(Integer machineId1Day6) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day6)
            machineId1Day6 = machineId1Day6 == 0 ? null : machineId1Day6;
        if (machineId1Day6!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day6)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day6, foreign key violation: xjobcard_xmachine_fk16");
        }
        setWasChanged(this.machineId1Day6 != null && !this.machineId1Day6.equals(machineId1Day6));
        this.machineId1Day6 = machineId1Day6;
    }

    public Integer getMachineId2Day6() {
        return machineId2Day6;
    }

    public void setMachineId2Day6(Integer machineId2Day6) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day6)
            machineId2Day6 = machineId2Day6 == 0 ? null : machineId2Day6;
        if (machineId2Day6!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day6)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day6, foreign key violation: xjobcard_xmachine_fk26");
        }
        setWasChanged(this.machineId2Day6 != null && !this.machineId2Day6.equals(machineId2Day6));
        this.machineId2Day6 = machineId2Day6;
    }

    public Integer getMachineId3Day6() {
        return machineId3Day6;
    }

    public void setMachineId3Day6(Integer machineId3Day6) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day6)
            machineId3Day6 = machineId3Day6 == 0 ? null : machineId3Day6;
        if (machineId3Day6!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day6)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day6, foreign key violation: xjobcard_xmachine_fk36");
        }
        setWasChanged(this.machineId3Day6 != null && !this.machineId3Day6.equals(machineId3Day6));
        this.machineId3Day6 = machineId3Day6;
    }

    public Integer getMachineId4Day6() {
        return machineId4Day6;
    }

    public void setMachineId4Day6(Integer machineId4Day6) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day6)
            machineId4Day6 = machineId4Day6 == 0 ? null : machineId4Day6;
        if (machineId4Day6!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day6)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day6, foreign key violation: xjobcard_xmachine_fk46");
        }
        setWasChanged(this.machineId4Day6 != null && !this.machineId4Day6.equals(machineId4Day6));
        this.machineId4Day6 = machineId4Day6;
    }

    public Integer getMachineId5Day6() {
        return machineId5Day6;
    }

    public void setMachineId5Day6(Integer machineId5Day6) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day6)
            machineId5Day6 = machineId5Day6 == 0 ? null : machineId5Day6;
        if (machineId5Day6!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day6)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day6, foreign key violation: xjobcard_xmachine_fk56");
        }
        setWasChanged(this.machineId5Day6 != null && !this.machineId5Day6.equals(machineId5Day6));
        this.machineId5Day6 = machineId5Day6;
    }

    public String getJob1Day7() {
        return job1Day7;
    }

    public void setJob1Day7(String job1Day7) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job1Day7 != null && !this.job1Day7.equals(job1Day7));
        this.job1Day7 = job1Day7;
    }

    public String getJob2Day7() {
        return job2Day7;
    }

    public void setJob2Day7(String job2Day7) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job2Day7 != null && !this.job2Day7.equals(job2Day7));
        this.job2Day7 = job2Day7;
    }

    public String getJob3Day7() {
        return job3Day7;
    }

    public void setJob3Day7(String job3Day7) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job3Day7 != null && !this.job3Day7.equals(job3Day7));
        this.job3Day7 = job3Day7;
    }

    public String getJob4Day7() {
        return job4Day7;
    }

    public void setJob4Day7(String job4Day7) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job4Day7 != null && !this.job4Day7.equals(job4Day7));
        this.job4Day7 = job4Day7;
    }

    public String getJob5Day7() {
        return job5Day7;
    }

    public void setJob5Day7(String job5Day7) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.job5Day7 != null && !this.job5Day7.equals(job5Day7));
        this.job5Day7 = job5Day7;
    }

    public Integer getMachineId1Day7() {
        return machineId1Day7;
    }

    public void setMachineId1Day7(Integer machineId1Day7) throws SQLException, ForeignKeyViolationException {
        if (null != machineId1Day7)
            machineId1Day7 = machineId1Day7 == 0 ? null : machineId1Day7;
        if (machineId1Day7!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId1Day7)) {
            throw new ForeignKeyViolationException("Can't set machine_id1_day7, foreign key violation: xjobcard_xmachine_fk17");
        }
        setWasChanged(this.machineId1Day7 != null && !this.machineId1Day7.equals(machineId1Day7));
        this.machineId1Day7 = machineId1Day7;
    }

    public Integer getMachineId2Day7() {
        return machineId2Day7;
    }

    public void setMachineId2Day7(Integer machineId2Day7) throws SQLException, ForeignKeyViolationException {
        if (null != machineId2Day7)
            machineId2Day7 = machineId2Day7 == 0 ? null : machineId2Day7;
        if (machineId2Day7!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId2Day7)) {
            throw new ForeignKeyViolationException("Can't set machine_id2_day7, foreign key violation: xjobcard_xmachine_fk27");
        }
        setWasChanged(this.machineId2Day7 != null && !this.machineId2Day7.equals(machineId2Day7));
        this.machineId2Day7 = machineId2Day7;
    }

    public Integer getMachineId3Day7() {
        return machineId3Day7;
    }

    public void setMachineId3Day7(Integer machineId3Day7) throws SQLException, ForeignKeyViolationException {
        if (null != machineId3Day7)
            machineId3Day7 = machineId3Day7 == 0 ? null : machineId3Day7;
        if (machineId3Day7!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId3Day7)) {
            throw new ForeignKeyViolationException("Can't set machine_id3_day7, foreign key violation: xjobcard_xmachine_fk37");
        }
        setWasChanged(this.machineId3Day7 != null && !this.machineId3Day7.equals(machineId3Day7));
        this.machineId3Day7 = machineId3Day7;
    }

    public Integer getMachineId4Day7() {
        return machineId4Day7;
    }

    public void setMachineId4Day7(Integer machineId4Day7) throws SQLException, ForeignKeyViolationException {
        if (null != machineId4Day7)
            machineId4Day7 = machineId4Day7 == 0 ? null : machineId4Day7;
        if (machineId4Day7!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId4Day7)) {
            throw new ForeignKeyViolationException("Can't set machine_id4_day7, foreign key violation: xjobcard_xmachine_fk47");
        }
        setWasChanged(this.machineId4Day7 != null && !this.machineId4Day7.equals(machineId4Day7));
        this.machineId4Day7 = machineId4Day7;
    }

    public Integer getMachineId5Day7() {
        return machineId5Day7;
    }

    public void setMachineId5Day7(Integer machineId5Day7) throws SQLException, ForeignKeyViolationException {
        if (null != machineId5Day7)
            machineId5Day7 = machineId5Day7 == 0 ? null : machineId5Day7;
        if (machineId5Day7!=null && !Xmachine.exists(getConnection(),"xmachine_id = " + machineId5Day7)) {
            throw new ForeignKeyViolationException("Can't set machine_id5_day7, foreign key violation: xjobcard_xmachine_fk57");
        }
        setWasChanged(this.machineId5Day7 != null && !this.machineId5Day7.equals(machineId5Day7));
        this.machineId5Day7 = machineId5Day7;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[74];
        columnValues[0] = getXjobcardId();
        columnValues[1] = getXemployeeId();
        columnValues[2] = getCarddate();
        columnValues[3] = getWeekEnding();
        columnValues[4] = getJob1Day1();
        columnValues[5] = getJob2Day1();
        columnValues[6] = getJob3Day1();
        columnValues[7] = getJob4Day1();
        columnValues[8] = getJob5Day1();
        columnValues[9] = getMachineId1Day1();
        columnValues[10] = getMachineId2Day1();
        columnValues[11] = getMachineId3Day1();
        columnValues[12] = getMachineId4Day1();
        columnValues[13] = getMachineId5Day1();
        columnValues[14] = getJob1Day2();
        columnValues[15] = getJob2Day2();
        columnValues[16] = getJob3Day2();
        columnValues[17] = getJob4Day2();
        columnValues[18] = getJob5Day2();
        columnValues[19] = getMachineId1Day2();
        columnValues[20] = getMachineId2Day2();
        columnValues[21] = getMachineId3Day2();
        columnValues[22] = getMachineId4Day2();
        columnValues[23] = getMachineId5Day2();
        columnValues[24] = getJob1Day3();
        columnValues[25] = getJob2Day3();
        columnValues[26] = getJob3Day3();
        columnValues[27] = getJob4Day3();
        columnValues[28] = getJob5Day3();
        columnValues[29] = getMachineId1Day3();
        columnValues[30] = getMachineId2Day3();
        columnValues[31] = getMachineId3Day3();
        columnValues[32] = getMachineId4Day3();
        columnValues[33] = getMachineId5Day3();
        columnValues[34] = getJob1Day4();
        columnValues[35] = getJob2Day4();
        columnValues[36] = getJob3Day4();
        columnValues[37] = getJob4Day4();
        columnValues[38] = getJob5Day4();
        columnValues[39] = getMachineId1Day4();
        columnValues[40] = getMachineId2Day4();
        columnValues[41] = getMachineId3Day4();
        columnValues[42] = getMachineId4Day4();
        columnValues[43] = getMachineId5Day4();
        columnValues[44] = getJob1Day5();
        columnValues[45] = getJob2Day5();
        columnValues[46] = getJob3Day5();
        columnValues[47] = getJob4Day5();
        columnValues[48] = getJob5Day5();
        columnValues[49] = getMachineId1Day5();
        columnValues[50] = getMachineId2Day5();
        columnValues[51] = getMachineId3Day5();
        columnValues[52] = getMachineId4Day5();
        columnValues[53] = getMachineId5Day5();
        columnValues[54] = getJob1Day6();
        columnValues[55] = getJob2Day6();
        columnValues[56] = getJob3Day6();
        columnValues[57] = getJob4Day6();
        columnValues[58] = getJob5Day6();
        columnValues[59] = getMachineId1Day6();
        columnValues[60] = getMachineId2Day6();
        columnValues[61] = getMachineId3Day6();
        columnValues[62] = getMachineId4Day6();
        columnValues[63] = getMachineId5Day6();
        columnValues[64] = getJob1Day7();
        columnValues[65] = getJob2Day7();
        columnValues[66] = getJob3Day7();
        columnValues[67] = getJob4Day7();
        columnValues[68] = getJob5Day7();
        columnValues[69] = getMachineId1Day7();
        columnValues[70] = getMachineId2Day7();
        columnValues[71] = getMachineId3Day7();
        columnValues[72] = getMachineId4Day7();
        columnValues[73] = getMachineId5Day7();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setXjobcardId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setXjobcardId(null);
        }
        try {
            setXemployeeId(Integer.parseInt(flds[1]));
        } catch(NumberFormatException ne) {
            setXemployeeId(null);
        }
        setCarddate(toDate(flds[2]));
        setWeekEnding(toDate(flds[3]));
        setJob1Day1(flds[4]);
        setJob2Day1(flds[5]);
        setJob3Day1(flds[6]);
        setJob4Day1(flds[7]);
        setJob5Day1(flds[8]);
        try {
            setMachineId1Day1(Integer.parseInt(flds[9]));
        } catch(NumberFormatException ne) {
            setMachineId1Day1(null);
        }
        try {
            setMachineId2Day1(Integer.parseInt(flds[10]));
        } catch(NumberFormatException ne) {
            setMachineId2Day1(null);
        }
        try {
            setMachineId3Day1(Integer.parseInt(flds[11]));
        } catch(NumberFormatException ne) {
            setMachineId3Day1(null);
        }
        try {
            setMachineId4Day1(Integer.parseInt(flds[12]));
        } catch(NumberFormatException ne) {
            setMachineId4Day1(null);
        }
        try {
            setMachineId5Day1(Integer.parseInt(flds[13]));
        } catch(NumberFormatException ne) {
            setMachineId5Day1(null);
        }
        setJob1Day2(flds[14]);
        setJob2Day2(flds[15]);
        setJob3Day2(flds[16]);
        setJob4Day2(flds[17]);
        setJob5Day2(flds[18]);
        try {
            setMachineId1Day2(Integer.parseInt(flds[19]));
        } catch(NumberFormatException ne) {
            setMachineId1Day2(null);
        }
        try {
            setMachineId2Day2(Integer.parseInt(flds[20]));
        } catch(NumberFormatException ne) {
            setMachineId2Day2(null);
        }
        try {
            setMachineId3Day2(Integer.parseInt(flds[21]));
        } catch(NumberFormatException ne) {
            setMachineId3Day2(null);
        }
        try {
            setMachineId4Day2(Integer.parseInt(flds[22]));
        } catch(NumberFormatException ne) {
            setMachineId4Day2(null);
        }
        try {
            setMachineId5Day2(Integer.parseInt(flds[23]));
        } catch(NumberFormatException ne) {
            setMachineId5Day2(null);
        }
        setJob1Day3(flds[24]);
        setJob2Day3(flds[25]);
        setJob3Day3(flds[26]);
        setJob4Day3(flds[27]);
        setJob5Day3(flds[28]);
        try {
            setMachineId1Day3(Integer.parseInt(flds[29]));
        } catch(NumberFormatException ne) {
            setMachineId1Day3(null);
        }
        try {
            setMachineId2Day3(Integer.parseInt(flds[30]));
        } catch(NumberFormatException ne) {
            setMachineId2Day3(null);
        }
        try {
            setMachineId3Day3(Integer.parseInt(flds[31]));
        } catch(NumberFormatException ne) {
            setMachineId3Day3(null);
        }
        try {
            setMachineId4Day3(Integer.parseInt(flds[32]));
        } catch(NumberFormatException ne) {
            setMachineId4Day3(null);
        }
        try {
            setMachineId5Day3(Integer.parseInt(flds[33]));
        } catch(NumberFormatException ne) {
            setMachineId5Day3(null);
        }
        setJob1Day4(flds[34]);
        setJob2Day4(flds[35]);
        setJob3Day4(flds[36]);
        setJob4Day4(flds[37]);
        setJob5Day4(flds[38]);
        try {
            setMachineId1Day4(Integer.parseInt(flds[39]));
        } catch(NumberFormatException ne) {
            setMachineId1Day4(null);
        }
        try {
            setMachineId2Day4(Integer.parseInt(flds[40]));
        } catch(NumberFormatException ne) {
            setMachineId2Day4(null);
        }
        try {
            setMachineId3Day4(Integer.parseInt(flds[41]));
        } catch(NumberFormatException ne) {
            setMachineId3Day4(null);
        }
        try {
            setMachineId4Day4(Integer.parseInt(flds[42]));
        } catch(NumberFormatException ne) {
            setMachineId4Day4(null);
        }
        try {
            setMachineId5Day4(Integer.parseInt(flds[43]));
        } catch(NumberFormatException ne) {
            setMachineId5Day4(null);
        }
        setJob1Day5(flds[44]);
        setJob2Day5(flds[45]);
        setJob3Day5(flds[46]);
        setJob4Day5(flds[47]);
        setJob5Day5(flds[48]);
        try {
            setMachineId1Day5(Integer.parseInt(flds[49]));
        } catch(NumberFormatException ne) {
            setMachineId1Day5(null);
        }
        try {
            setMachineId2Day5(Integer.parseInt(flds[50]));
        } catch(NumberFormatException ne) {
            setMachineId2Day5(null);
        }
        try {
            setMachineId3Day5(Integer.parseInt(flds[51]));
        } catch(NumberFormatException ne) {
            setMachineId3Day5(null);
        }
        try {
            setMachineId4Day5(Integer.parseInt(flds[52]));
        } catch(NumberFormatException ne) {
            setMachineId4Day5(null);
        }
        try {
            setMachineId5Day5(Integer.parseInt(flds[53]));
        } catch(NumberFormatException ne) {
            setMachineId5Day5(null);
        }
        setJob1Day6(flds[54]);
        setJob2Day6(flds[55]);
        setJob3Day6(flds[56]);
        setJob4Day6(flds[57]);
        setJob5Day6(flds[58]);
        try {
            setMachineId1Day6(Integer.parseInt(flds[59]));
        } catch(NumberFormatException ne) {
            setMachineId1Day6(null);
        }
        try {
            setMachineId2Day6(Integer.parseInt(flds[60]));
        } catch(NumberFormatException ne) {
            setMachineId2Day6(null);
        }
        try {
            setMachineId3Day6(Integer.parseInt(flds[61]));
        } catch(NumberFormatException ne) {
            setMachineId3Day6(null);
        }
        try {
            setMachineId4Day6(Integer.parseInt(flds[62]));
        } catch(NumberFormatException ne) {
            setMachineId4Day6(null);
        }
        try {
            setMachineId5Day6(Integer.parseInt(flds[63]));
        } catch(NumberFormatException ne) {
            setMachineId5Day6(null);
        }
        setJob1Day7(flds[64]);
        setJob2Day7(flds[65]);
        setJob3Day7(flds[66]);
        setJob4Day7(flds[67]);
        setJob5Day7(flds[68]);
        try {
            setMachineId1Day7(Integer.parseInt(flds[69]));
        } catch(NumberFormatException ne) {
            setMachineId1Day7(null);
        }
        try {
            setMachineId2Day7(Integer.parseInt(flds[70]));
        } catch(NumberFormatException ne) {
            setMachineId2Day7(null);
        }
        try {
            setMachineId3Day7(Integer.parseInt(flds[71]));
        } catch(NumberFormatException ne) {
            setMachineId3Day7(null);
        }
        try {
            setMachineId4Day7(Integer.parseInt(flds[72]));
        } catch(NumberFormatException ne) {
            setMachineId4Day7(null);
        }
        try {
            setMachineId5Day7(Integer.parseInt(flds[73]));
        } catch(NumberFormatException ne) {
            setMachineId5Day7(null);
        }
    }
}
