// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Tue Aug 07 08:44:26 EEST 2012
// generated file: do not modify
package com.xlend.orm;

import com.xlend.orm.dbobject.DbObject;
import com.xlend.orm.dbobject.ForeignKeyViolationException;
import com.xlend.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Xstocks extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer xstocksId = null;
    private String name = null;
    private String description = null;

    public Xstocks(Connection connection) {
        super(connection, "xstocks", "xstocks_id");
        setColumnNames(new String[]{"xstocks_id", "name", "description"});
    }

    public Xstocks(Connection connection, Integer xstocksId, String name, String description) {
        super(connection, "xstocks", "xstocks_id");
        setNew(xstocksId.intValue() <= 0);
//        if (xstocksId.intValue() != 0) {
            this.xstocksId = xstocksId;
//        }
        this.name = name;
        this.description = description;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Xstocks xstocks = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xstocks_id,name,description FROM xstocks WHERE xstocks_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                xstocks = new Xstocks(getConnection());
                xstocks.setXstocksId(new Integer(rs.getInt(1)));
                xstocks.setName(rs.getString(2));
                xstocks.setDescription(rs.getString(3));
                xstocks.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return xstocks;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO xstocks ("+(getXstocksId().intValue()!=0?"xstocks_id,":"")+"name,description) values("+(getXstocksId().intValue()!=0?"?,":"")+"?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getXstocksId().intValue()!=0) {
                 ps.setObject(++n, getXstocksId());
             }
             ps.setObject(++n, getName());
             ps.setObject(++n, getDescription());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getXstocksId().intValue()==0) {
             stmt = "SELECT max(xstocks_id) FROM xstocks";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setXstocksId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE xstocks " +
                    "SET name = ?, description = ?" + 
                    " WHERE xstocks_id = " + getXstocksId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getName());
                ps.setObject(2, getDescription());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (Xpartstocks.exists(getConnection(),"xstocks_id = " + getXstocksId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: xpartstocks_xstocks_fk");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM xstocks " +
                "WHERE xstocks_id = " + getXstocksId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setXstocksId(new Integer(-getXstocksId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getXstocksId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xstocks_id,name,description FROM xstocks " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Xstocks(con,new Integer(rs.getInt(1)),rs.getString(2),rs.getString(3)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Xstocks[] objects = new Xstocks[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Xstocks xstocks = (Xstocks) lst.get(i);
            objects[i] = xstocks;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT xstocks_id FROM xstocks " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getXstocksId() + getDelimiter();
    //}

    public Integer getXstocksId() {
        return xstocksId;
    }

    public void setXstocksId(Integer xstocksId) throws ForeignKeyViolationException {
        setWasChanged(this.xstocksId != null && this.xstocksId != xstocksId);
        this.xstocksId = xstocksId;
        setNew(xstocksId.intValue() == 0);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.name != null && !this.name.equals(name));
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.description != null && !this.description.equals(description));
        this.description = description;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[3];
        columnValues[0] = getXstocksId();
        columnValues[1] = getName();
        columnValues[2] = getDescription();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setXstocksId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setXstocksId(null);
        }
        setName(flds[1]);
        setDescription(flds[2]);
    }
}
