drop table tmp_statusctics if exist;
create temporary table tmp_statistics as
select 'cbitems' tablename,count(*) cnt,max(stamp) laststamp from cbitems union 
select 'clientprofile',count(*),max(stamp) from clientprofile union 
select 'picture',count(*),max(stamp) from picture union
select 'profile',count(*),max(stamp) from profile union
select 'reportgroup',count(*),max(stamp) from  reportgroup union
select 'sheet',count(*),max(stamp) from sheet union
select 'userprofile',count(*),max(stamp) from  userprofile union
select 'usersheet',count(*),max(stamp) from  usersheet union
select 'xabsenteeism',count(*),max(stamp) from  xabsenteeism union
select 'xaccounts',count(*),max(stamp) from  xaccounts union
select 'xaddstocks',count(*),max(stamp) from  xaddstocks union
select 'xappforleave',count(*),max(stamp) from  xappforleave union
select 'xbankbalance',count(*),max(stamp) from  xbankbalance union
select 'xbankbalancepart',count(*),max(stamp) from  xbankbalancepart union
select 'xbookouts',count(*),max(stamp) from  xbookouts union
select 'xbreakconsume',count(*),max(stamp) from  xbreakconsume union
select 'xbreakdown',count(*),max(stamp) from  xbreakdown union
select 'xclient',count(*),max(stamp) from xclient union
select 'xconsume',count(*),max(stamp) from xconsume union
select 'xcontract',count(*),max(stamp) from  xcontract union 
select 'xcontractpage',count(*),max(stamp) from  xcontractpage union
select 'xdieselcard',count(*),max(stamp) from  xdieselcard union
select 'xdieselpchs',count(*),max(stamp) from  xdieselpchs union
select 'xemployee',count(*),max(stamp) from  xemployee union
select 'xemployeeincident',count(*),max(stamp) from  xemployeeincident union
select 'xfuel',count(*),max(stamp) from xfuel union
select 'xhourcompare',count(*),max(stamp) from  xhourcompare union
select 'xhourcompareday',count(*),max(stamp) from  xhourcompareday union
select 'xincidents',count(*),max(stamp) from  xincidents union
select 'xissuing',count(*),max(stamp) from xissuing union
select 'xjobcard',count(*),max(stamp) from xjobcard union
select 'xloans',count(*),max(stamp) from xloans union
select 'xlowbed',count(*),max(stamp) from xlowbed union
select 'xmachine',count(*),max(stamp) from xmachine union 
select 'xmachineincident',count(*),max(stamp) from  xmachineincident union
select 'xmachrentalrate',count(*),max(stamp) from  xmachrentalrate union
select 'xmachrentalrateitm',count(*),max(stamp) from  xmachrentalrateitm union
select 'xmachtype',count(*),max(stamp) from  xmachtype union
select 'xopclocksheet',count(*),max(stamp) from  xopclocksheet union
select 'xopmachassing',count(*),max(stamp) from  xopmachassing union
select 'xorder',count(*),max(stamp) from xorder union
select 'xorderitem',count(*),max(stamp) from  xorderitem union
select 'xorderpage',count(*),max(stamp) from  xorderpage union
select 'xpaidmethod',count(*),max(stamp) from  xpaidmethod union
select 'xpartcategory',count(*),max(stamp) from  xpartcategory union
select 'xparts',count(*),max(stamp) from xparts union
select 'xpayment',count(*),max(stamp) from xpayment union
select 'xposition',count(*),max(stamp) from  xposition union
select 'xquotation',count(*),max(stamp) from  xquotation union
select 'xquotationpage',count(*),max(stamp) from  xquotationpage union
select 'xsalary',count(*),max(stamp) from xsalary union
select 'xsalarylist',count(*),max(stamp) from  xsalarylist union
select 'xsite',count(*),max(stamp) from xsite union
select 'xsitediary',count(*),max(stamp) from  xsitediary union
select 'xsitediaryitem',count(*),max(stamp) from  xsitediaryitem union
select 'xsupplier',count(*),max(stamp) from  xsupplier union
select 'xtimesheet',count(*),max(stamp) from  xtimesheet union
select 'xtransscheduleitm',count(*),max(stamp) from  xtransscheduleitm union
select 'xtrip',count(*),max(stamp) from xtrip union
select 'xtripsheet',count(*),max(stamp) from  xtripsheet union
select 'xtripsheetpart',count(*),max(stamp) from  xtripsheetpart union
select 'xwage',count(*),max(stamp) from xwage union
select 'xwagesum',count(*),max(stamp) from xwagesum union
select 'xwagesumitem',count(*),max(stamp) from  xwagesumitem;

select * from tmp_statistics;
select sum(cnt),max(laststamp) from tmp_statistics;
